version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
    ".github/**",
    "art/**",
    "examples/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  module_system = "commonjs"
  environment = ["nodejs"]